oasis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('branch/<str:name>', views.branches, name="branch"),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectoasis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oasis.urls')),
]

oasis/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Branch(models.Model):

    name = models.CharField(max_length=255)
    pastor = models.CharField(max_length=255)
    s_pastor = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255)
    number = PhoneNumberField(region='ZA')
    history = models.TextField()
    image = models.ImageField(upload_to='media/')

    def __str__(self):

        return self.name

oasis/forms.py
from django import forms


class ContactForm(forms.Form):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

oasis/views.py
from .models import Branch
from .forms import ContactForm
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
# Create your views here.


def home(request):

    context = {
        'page_title': 'Home',
        'branches': list(Branch.objects.all())
    }

    return render(request, 'oasis/home.html', context)


def contact(request):

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            sender_first = request.POST['first_name']
            sender_last = request.POST['last_name']
            sender_email = request.POST['email']
            subject = request.POST['subject']
            sender_message = request.POST['message']

            try:
                send_mail(
                    f'{subject} inquiry by {sender_first} {sender_last}',
                    sender_message,
                    sender_email,
                    ['rhulanimogotsi@gmail.com']
                )

                messages.success(request, 'Message sent! Expect to hear from us soon!')
                return redirect('home')
            except BadHeaderError:
                return HttpResponse('Invalid Header')
    else:
        form = ContactForm()

    context = {
        'page_title': 'Contact',
        'ContactForm': form,
        'branches': [branch for branch in Branch.objects.all()],
    }

    return render(request, 'oasis/contact.html', context)


def branches(request, name):

    branch = Branch.objects.get(name=name)

    context = {
        'branch': branch,
        'page_title': 'Branches',
        'branches': [branch for branch in Branch.objects.all()],
    }

    return render(request, 'oasis/branch.html', context)

oasis/templates/oasis/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/f8dced6eec.js" crossorigin="anonymous"></script>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'oasis/base.css' %}">
    
    {% block styles %}{% endblock %}

    <title>Oasis of Life Family Church</title>
</head>
<body>
    <header>
        <div class="header-backdrop">
            <nav class="navbar navbar-expand-md">
                <div class="nav-container container-fluid justify-content-center">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    
                    <div id="main-nav" class="collapse navbar-collapse justify-content-between m-0">
                        <div class="navbar-block navbar-left">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="{% url 'home' %}" class="{% if page_title == 'Home' %}live{% endif %} nav-link">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="" class="{% if page_title == 'Branches' %}live{% endif %} nav-link">Branches</a>
                                    <div class="branches-dropdown p-2">
                                        {% for branch in branches %}
                                            <a class="product-link" href="{% url 'branch' branch.name %}">{{branch}}</a>
                                        {% endfor %}
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a href="" class="{% if page_title == 'NexGen Youth' %}live{% endif %} nav-link">NexGen Youth</a>
                                </li>
                            </ul>
                        </div>
                        <div class="navbar-block navbar-right">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="" class="{% if page_title == 'Projects' %}live{% endif %} nav-link">Projects</a>
                                </li>
                                <li class="nav-item">
                                    <a href="" class="{% if page_title == 'Family' %}live{% endif %} nav-link">Meet the family</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'contact' %}" class="{% if page_title == 'Contact' %}live{% endif %} nav-link">Contact</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <a href="/" class="navbar-brand m-0 p-4">
                        <img alt="Oasis logo" src="{% static 'oasis/images/oasis-logo.png' %}" class="navbar-logo img-fluid" alt="Oasis logo">
                    </a>
                </div>
            </nav>
            {% block header %}
            {% endblock %}
        </div>
    </header>
    {% block bodycontent %}
    {% endblock %}
    <script src="{% static 'oasis/home.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

oasis/templates/oasis/branch.html
{% extends 'oasis/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'oasis/branch.css' %}">
{% endblock %}

{% block header %}
<div class="header-content px-5">
    <div class="header-image">
        <img src="{{branch.image.url}}" class="header-img">
    </div>
    <h2 class="display-2 header-heading">
        {{branch}}
        <hr class="header-hr mt-2">
    </h2>
</div>
{% endblock %}
{% block bodycontent %}
    <div class="scripture-divider my-5 text-center">
        <p class="divider-title fw-bold"><i>"They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer. "</p></i>
        <p class="divider-verse">Acts 2:42</p>
    </div>
    <section id="branch-contact" class="my-5">
        <div class="container-xl contact-container p-0">
            <div class="display-3 contact-header ms-3">Reach Out:</div>
            <div class="contact-content">
                <div class="address-block">
                    <i class="fa-solid fa-house block-icon pb-4"></i>
                    <h2 class="block-title">Address</h2>
                    <h5 class="block-content px-5 pt-4">{{branch.address}}</h5>
                </div>
                <div class="number-block">
                    <i class="fa-solid fa-phone block-icon pb-4"></i>
                    <h2 class="block-title">Phone Number</h2>
                    <h5 class="block-content px-5 pt-4">{{branch.number}}</h5>
                </div>
            </div>
        </div>
    </section>
    <section id="history" class="my-5">
        <div class="container-xl history-container">
            <img src="{% static 'oasis/images/oasis-logo.png' %}" alt="" class="welcome-letterhead my-3">
        <h1 class="display-3 history-heading">History</h1>
        <hr class="my-5">
        <p class="history-text">{{branch.history}}</p>
        </div>
    </section>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} m-5">
                    <i class="fa-solid fa-circle-info"></i>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
{% endblock %}

oasis/templates/oasis/contact.html
{% extends 'oasis/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'oasis/contact.css' %}">
{% endblock %}

{% block header %}
<div class="header-content p-5">
    <h2 class="display-2 header-heading mt-5">
        Contact Us
    </h2>
</div>
{% endblock %}
{% block bodycontent %}
    <div class="scripture-divider my-5">
        <p class="divider-title fw-bold"><i>"Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone"</p></i>
        <p class="divider-verse">Colossians 4:6</p>
    </div>
    <section id="contact">
        <div class="container-xl contact-container">
            <div class="contact-letterhead mt-4">
                <img src="{% static 'oasis/images/oasis-logo.png' %}" alt="">
            </div>
            <h4 class="display-4 text-center contact-title py-3">Speak to us</h4>
            <hr class="contact-hr mb-5">
            <form action="" method="post" class="px-3">
                {% csrf_token %}
                <div class="row form-block">
                    <div class="sub-block col-lg-6 px-2">
                        <label for="id_first_name">First name:</label>
                        <input type="text" name="first_name" required="" id="id_first_name">
                    </div>
                    <div class="sub-block col-lg-6 px-2">
                        <label for="id_last_name">Last name:</label>
                        <input type="text" name="last_name" required="" id="id_last_name">
                    </div>
                </div>
                <div class="row form-block">
                    <div class="sub-block col-lg-6 px-2">
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" maxlength="320" required="" id="id_email">
                    </div>
                    <div class="sub-block col-lg-6 px-2">
                        <label for="id_subject">Subject:</label>
                        <input type="text" name="subject" required="" id="id_subject">
                    </div>
                </div>
                <div class="sub-block">
                    <label for="id_message">Message:</label>
                    <textarea name="message" cols="40" rows="10" required="" id="id_message"></textarea>
                </div>
                <button type="submit" id="submit" class="px-5 py-2 my-2">Submit</button>
            </form>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} m-5">
                    <i class="fa-solid fa-circle-info"></i>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </section>
{% endblock %}

oasis/templates/oasis/home.html
{% extends 'oasis/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'oasis/home.css' %}">
{% endblock %}


{% block header %}
    <div class="header-content p-5">
        <h2 class="display-5 header-title">Oasis of Life Family Church:</h2>
        <h2 class="display-2 header-heading mt-5">
            The church that <br>
            <span class="fade-in">loves and cares</span>
            <br>for God's people
        </h2>
    </div>
{% endblock %}
{% block bodycontent %}
    <div class="scripture-divider my-5">
        <p class="divider-title fw-bold"><i>"...For where two or three gather in my name, there am I with them."</p></i>
        <p class="divider-verse">Matthew 18:20</p>
    </div>
    <section id="welcome" class="p-5">
        <div class="welcome-container container-xl justify-content-end">
            <div class="welcome-content">
                <img src="{% static 'oasis/images/oasis-logo.png' %}" alt="" class="welcome-letterhead my-3">
                <h2 class="welcome-title">
                    Welcome to<br><span>Oasis of Life Family Church</span>
                </h2>
                <hr class="my-4">
                <p class="welcome-text px-3">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
                    Similique cupiditate amet, libero aperiam esse dolorum, 
                    velit excepturi a dolorem asperiores cumque ducimus quod,
                    molestiae et provident enim modi quis distinctio.
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
                    Similique cupiditate amet, libero aperiam esse dolorum
                </p>
                <p class="welcome-writers">Apostle I.N Sithole and Prophet S.H Sithole</p>
            </div>
        </div>
    </section>
    <section id="values">
        <div class="values-container container-xl">
            <div class="values-header my-5">
                <img src="{% static 'oasis/images/oasis-logo.png' %}" alt="" class="welcome-letterhead my-3">
                <h1 class="display-3 values-heading">Our Values</h1>
                <hr class="my-5">
            </div>
            <div class="row values-row">
                <div class="value-column col-lg-4">
                    <div class="card value-card justify-content-center">
                        <h5 class="value-title mt-3">Belong</h5>
                        <hr class="my-2">
                        <p class="value-text px-5">
                            We believe our utmost desire is to get 
                            the people of God to belong irrespective of 
                            where and who they are, what class and or 
                            status they bare.
                        </p>
                    </div>
                </div>
                <div class="value-column col-lg-4">
                    <div class="card value-card justify-content-center">
                        <h5 class="value-title mt-3">Believe</h5>
                        <hr class="my-2">
                        <p class="value-text px-5">
                            That when the people of God know and 
                            understand the vision and mission, will 
                            be willing to fulfil the mandate given 
                            to the local church.
                        </p>
                    </div>
                </div>
                <div class="value-column col-lg-4">
                    <div class="card value-card justify-content-center">
                        <h5 class="value-title mt-3">Behave</h5>
                        <hr class="my-2">
                        <p class="value-text px-5">
                            We believe that when people embrace the 
                            vision and mission they will be taught 
                            how to behave and follow the doctrine 
                            of Christ.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}